# Generated by Django 3.2.7 on 2021-09-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='isClamed',
        ),
        migrations.AddField(
            model_name='bike',
            name='isClaimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bike',
            name='inWifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='macAddress',
            field=models.TextField(max_length=17),
        ),
        migrations.AlterField(
            model_name='bike',
            name='needsRepair',
            field=models.BooleanField(default=False),
        ),
    ]
