# Generated by Django 3.2.7 on 2021-09-30 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_bike_claimedby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='inWifi',
            new_name='onCampus',
        ),
        migrations.AddField(
            model_name='bike',
            name='lastContactWithServer',
            field=models.TimeField(default=datetime.datetime(2021, 9, 30, 21, 44, 43, 170139, tzinfo=utc), verbose_name=datetime.datetime(2021, 9, 30, 21, 43, 43, 624934, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
